# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 17:51
from __future__ import unicode_literals

import Faculty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('DOB', models.DateField(default=b'1976-02-11')),
                ('faculty_code', models.CharField(max_length=50)),
                ('salary', models.IntegerField(default=10)),
                ('teaching_from', models.PositiveIntegerField(default=0)),
                ('subjects_experience', models.CharField(max_length=250)),
                ('projects', models.TextField(max_length=300)),
                ('caste_type', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField(default=0)),
                ('religion', models.CharField(max_length=20)),
                ('sub_caste', models.CharField(max_length=30)),
                ('handicapped', models.BooleanField(default=0)),
                ('nationality', models.CharField(max_length=50)),
                ('emergency_name', models.CharField(max_length=50)),
                ('emergency_mobile', models.BigIntegerField()),
                ('emergency_relation', models.CharField(max_length=50)),
                ('emergency_address', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=50)),
                ('father_profession', models.CharField(max_length=30)),
                ('father_designation', models.CharField(max_length=30)),
                ('father_mobile', models.BigIntegerField(blank=True)),
                ('father_email', models.EmailField(blank=True, max_length=254)),
                ('mother_name', models.CharField(max_length=50)),
                ('mother_profession', models.CharField(max_length=30)),
                ('mother_designation', models.CharField(max_length=30)),
                ('mother_mobile', models.BigIntegerField()),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('permanent_address', models.CharField(max_length=100)),
                ('permanent_state', models.CharField(max_length=50)),
                ('permanent_city', models.CharField(max_length=50)),
                ('permanent_pin_code', models.PositiveIntegerField()),
                ('permanent_country', models.CharField(max_length=50)),
                ('current_address', models.CharField(max_length=100)),
                ('current_state', models.CharField(max_length=50)),
                ('current_city', models.CharField(max_length=50)),
                ('current_pin_code', models.PositiveIntegerField()),
                ('current_country', models.CharField(max_length=50)),
                ('doc', models.FileField(upload_to=Faculty.models.user_directory_path)),
                ('doc_profile_pic', models.FileField(upload_to=Faculty.models.user_directory_path)),
            ],
        ),
    ]
