# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=10)),
                ('HOD', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Faculty.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_code', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('divsion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.Division')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=2)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.Branch')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.Year'),
        ),
    ]
