# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20170723_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='mobile',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='nationality',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='religion',
            field=models.CharField(max_length=20),
        ),
    ]
