# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20170725_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='gr_number',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
