# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 10:54
from __future__ import unicode_literals

import Registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_auto_20170723_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='doc_profile_pic',
            field=models.FileField(upload_to=Registration.models.student_directory_path),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='mobile',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='religion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='sub_caste',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
