# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 10:54
from __future__ import unicode_literals

import Registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_auto_20170723_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='doc_profile_pic',
            field=models.ImageField(upload_to=Registration.models.student_directory_path),
        ),
    ]
