countries = [('India', 'India'),
             ('Afghanistan', 'Afghanistan'),
             ('Albania', 'Albania'),
             ('Algeria', 'Algeria'),
             ('Andorra', 'Andorra'),
             ('Angola', 'Angola'),
             ('Antigua and Barbuda', 'Antigua and Barbuda'),
             ('Argentina', 'Argentina'),
             ('Armenia', 'Armenia'),
             ('Australia', 'Australia'),
             ('Christmas Island', 'Christmas Island'),
             ('Norfolk Island', 'Norfolk Island'),
             ('Austria', 'Austria'),
             ('Azerbaijan', 'Azerbaijan'),
             ('Bahamas', 'Bahamas'),
             ('Bahrain', 'Bahrain'),
             ('Bangladesh', 'Bangladesh'),
             ('Barbados', 'Barbados'),
             ('Belarus', 'Belarus'),
             ('Belgium', 'Belgium'),
             ('Belize', 'Belize'),
             ('Benin', 'Benin'),
             ('Bhutan', 'Bhutan'),
             ('Bolivia', 'Bolivia'),
             ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'),
             ('Republika Srpska', 'Republika Srpska'),
             ('Botswana', 'Botswana'),
             ('Brazil', 'Brazil'),
             ('Brunei', 'Brunei'),
             ('Bulgaria', 'Bulgaria'),
             ('Burkina Faso', 'Burkina Faso'),
             ('Burma', 'Burma'),
             ('Burundi', 'Burundi'),
             ('Cambodia', 'Cambodia'),
             ('Cameroon', 'Cameroon'),
             ('Canada', 'Canada'),
             ('Cape Verde', 'Cape Verde'),
             ('Central African Republic', 'Central African Republic'),
             ('Chad', 'Chad'),
             ('Chile', 'Chile'),
             ('China', 'China'),
             ('Hong Kong', 'Hong Kong'),
             ('Macau', 'Macau'),
             ('Colombia', 'Colombia'),
             ('Comoros', 'Comoros'),
             ('Congo', 'Congo'),
             ('Congo', 'Congo'),
             (' Republic of the', ' Republic of the'),
             ('Costa Rica', 'Costa Rica'),
             ('Croatia', 'Croatia'),
             ('Cuba', 'Cuba'),
             ('Cyprus', 'Cyprus'),
             ('Czech Republic', 'Czech Republic'),
             ('Denmark', 'Denmark'),
             ('Faroe Islands', 'Faroe Islands'),
             ('Greenland', 'Greenland'),
             ('Djibouti', 'Djibouti'),
             ('Dominica', 'Dominica'),
             ('Dominican Republic', 'Dominican Republic'),
             ('East Timor', 'East Timor'),
             ('Ecuador', 'Ecuador'),
             ('Egypt', 'Egypt'),
             ('El Salvador', 'El Salvador'),
             ('Equatorial Guinea', 'Equatorial Guinea'),
             ('Eritrea', 'Eritrea'),
             ('Estonia', 'Estonia'),
             ('Ethiopia', 'Ethiopia'),
             ('Fiji', 'Fiji'),
             ('Finland', 'Finland'),
             ('Åland', 'Åland'),
             ('France', 'France'),
             ('Clipperton Island', 'Clipperton Island'),
             ('French Polynesia', 'French Polynesia'),
             ('New Caledonia', 'New Caledonia'),
             ('Saint Barthélemy', 'Saint Barthélemy'),
             ('Saint Martin', 'Saint Martin'),
             ('Wallis and Futuna', 'Wallis and Futuna'),
             ('Gabon', 'Gabon'),
             ('Gambia', 'Gambia'),
             (' The', ' The'),
             ('Georgia', 'Georgia'),
             ('Germany', 'Germany'),
             ('Ghana', 'Ghana'),
             ('Greece', 'Greece'),
             ('Grenada', 'Grenada'),
             ('Guatemala', 'Guatemala'),
             ('Guinea', 'Guinea'),
             ('Guinea-Bissau', 'Guinea-Bissau'),
             ('Guyana', 'Guyana'),
             ('Haiti', 'Haiti'),
             ('Honduras', 'Honduras'),
             ('Hungary', 'Hungary'),
             ('Iceland', 'Iceland'),
             ('Indonesia', 'Indonesia'),
             ('Iran', 'Iran'),
             ('Iraq', 'Iraq'),
             ('Ireland', 'Ireland'),
             ('Israel', 'Israel'),
             ('Italy', 'Italy'),
             ('Ivory Coast', 'Ivory Coast'),
             ('Jamaica', 'Jamaica'),
             ('Japan', 'Japan'),
             ('Jordan', 'Jordan'),
             ('Kazakhstan', 'Kazakhstan'),
             ('Kenya', 'Kenya'),
             ('Kiribati', 'Kiribati'),
             ('Korea', 'Korea'),
             (' North', ' North'),
             ('Korea', 'Korea'),
             (' South', ' South'),
             ('Kuwait', 'Kuwait'),
             ('Kyrgyzstan', 'Kyrgyzstan'),
             ('Laos', 'Laos'),
             ('Latvia', 'Latvia'),
             ('Lebanon', 'Lebanon'),
             ('Lesotho', 'Lesotho'),
             ('Liberia', 'Liberia'),
             ('Libya', 'Libya'),
             ('Cyrenaica', 'Cyrenaica'),
             ('Liechtenstein', 'Liechtenstein'),
             ('Lithuania', 'Lithuania'),
             ('Luxembourg', 'Luxembourg'),
             ('Macedonia', 'Macedonia'),
             ('Madagascar', 'Madagascar'),
             ('Malawi', 'Malawi'),
             ('Malaysia', 'Malaysia'),
             ('Maldives', 'Maldives'),
             ('Mali', 'Mali'),
             ('Malta', 'Malta'),
             ('Marshall Islands', 'Marshall Islands'),
             ('Mauritania', 'Mauritania'),
             ('Mauritius', 'Mauritius'),
             ('Mexico', 'Mexico'),
             ('Micronesia', 'Micronesia'),
             ('Federated States of', 'Federated States of'),
             ('Moldova', 'Moldova'),
             ('Monaco', 'Monaco'),
             ('Mongolia', 'Mongolia'),
             ('Montenegro', 'Montenegro'),
             ('Morocco', 'Morocco'),
             ('Mozambique', 'Mozambique'),
             ('Namibia', 'Namibia'),
             ('Nauru', 'Nauru'),
             ('Nepal', 'Nepal'),
             ('Netherlands', 'Netherlands'),
             ('Netherlands', 'Netherlands'),
             ('Aruba', 'Aruba'),
             ('Curaçao', 'Curaçao'),
             ('Sint Maarten', 'Sint Maarten'),
             ('New Zealand', 'New Zealand'),
             ('Ross Dependency', 'Ross Dependency'),
             ('Tokelau', 'Tokelau'),
             ('Cook Islands', 'Cook Islands'),
             ('Niue', 'Niue'),
             ('Nicaragua', 'Nicaragua'),
             ('Niger', 'Niger'),
             ('Nigeria', 'Nigeria'),
             ('Norway', 'Norway'),
             ('Oman', 'Oman'),
             ('Pakistan', 'Pakistan'),
             ('Azad Kashmir', 'Azad Kashmir'),
             ('Gilgit–Baltistan', 'Gilgit–Baltistan'),
             ('Palau', 'Palau'),
             ('Palestine', 'Palestine'),
             ('Panama', 'Panama'),
             ('Papua New Guinea', 'Papua New Guinea'),
             ('Paraguay', 'Paraguay'),
             ('Peru', 'Peru'),
             ('Philippines', 'Philippines'),
             ('Poland', 'Poland'),
             ('Portugal', 'Portugal'),
             ('Qatar', 'Qatar'),
             ('Romania', 'Romania'),
             ('Russia', 'Russia'),
             ('Rwanda', 'Rwanda'),
             ('Saint Lucia', 'Saint Lucia'),
             ('Samoa', 'Samoa'),
             ('San Marino', 'San Marino'),
             ('Saudi Arabia', 'Saudi Arabia'),
             ('Senegal', 'Senegal'),
             ('Serbia', 'Serbia'),
             ('Seychelles', 'Seychelles'),
             ('Sierra Leone', 'Sierra Leone'),
             ('Singapore', 'Singapore'),
             ('Slovakia', 'Slovakia'),
             ('Slovenia', 'Slovenia'),
             ('Solomon Islands', 'Solomon Islands'),
             ('Somalia', 'Somalia'),
             ('South Africa', 'South Africa'),
             ('South Sudan', 'South Sudan'),
             ('Spain', 'Spain'),
             ('Sri Lanka', 'Sri Lanka'),
             ('Sudan', 'Sudan'),
             ('Suriname', 'Suriname'),
             ('Swaziland', 'Swaziland'),
             ('Sweden', 'Sweden'),
             ('Switzerland', 'Switzerland'),
             ('Syria', 'Syria'),
             ('Tajikistan', 'Tajikistan'),
             ('Tanzania', 'Tanzania'),
             ('Thailand', 'Thailand'),
             ('Togo', 'Togo'),
             ('Tonga', 'Tonga'),
             ('Trinidad and Tobago', 'Trinidad and Tobago'),
             ('Tunisia', 'Tunisia'),
             ('Turkey', 'Turkey'),
             ('Turkmenistan', 'Turkmenistan'),
             ('Tuvalu', 'Tuvalu'),
             ('Uganda', 'Uganda'),
             ('Ukraine', 'Ukraine'),
             ('United Arab Emirates', 'United Arab Emirates'),
             ('United Kingdom', 'United Kingdom'),
             ('Akrotiri and Dhekelia', 'Akrotiri and Dhekelia'),
             ('Anguilla', 'Anguilla'),
             ('Bermuda', 'Bermuda'),
             ('British Virgin Islands', 'British Virgin Islands'),
             ('Cayman Islands', 'Cayman Islands'),
             ('Falkland Islands', 'Falkland Islands'),
             ('Gibraltar', 'Gibraltar'),
             ('Montserrat', 'Montserrat'),
             ('Pitcairn Islands', 'Pitcairn Islands'),
             ('Saint Helena', 'Saint Helena'),
             ('Turks and Caicos Islands', 'Turks and Caicos Islands'),
             ('British Antarctic Territory', 'British Antarctic Territory'),
             ('Guernsey', 'Guernsey'),
             ('Alderney', 'Alderney'),
             ('Herm', 'Herm'),
             ('Sark', 'Sark'),
             ('Isle of Man', 'Isle of Man'),
             ('Jersey', 'Jersey'),
             ('United States', 'United States'),
             ('American Samoa', 'American Samoa'),
             ('Guam', 'Guam'),
             ('Northern Mariana Islands', 'Northern Mariana Islands'),
             ('Puerto Rico', 'Puerto Rico'),
             ('U.S. Virgin Islands', 'U.S. Virgin Islands'),
             ('Marshall Islands', 'Marshall Islands'),
             ('Micronesia', 'Micronesia'),
             ('Palau', 'Palau'),
             ('Uruguay', 'Uruguay'),
             ('Uzbekistan', 'Uzbekistan'),
             ('Vanuatu', 'Vanuatu'),
             ('Vatican City', 'Vatican City'),
             ('Venezuela', 'Venezuela'),
             ('Vietnam', 'Vietnam'),
             ('Yemen', 'Yemen'),
             ('Zambia', 'Zambia'),
             ('Zimbabwe', 'Zimbabwe'),
             ('Abkhazia', 'Abkhazia'),
             ('Cook Islands', 'Cook Islands'),
             ('Kosovo', 'Kosovo'),
             ('Nagorno-Karabakh', 'Nagorno-Karabakh'),
             ('Niue', 'Niue'),
             ('Northern Cyprus', 'Northern Cyprus'),
             ('Somaliland', 'Somaliland'),
             ('South Ossetia', 'South Ossetia'),
             ('Taiwan', 'Taiwan'),
             ('Transnistria', 'Transnistria')]
